insert into produtos (id, nome, descricao, preco) values (1, 'Rice - Basmati', 'erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer', 36);
insert into produtos (id, nome, descricao, preco) values (2, 'Turnip - Wax', 'eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna', 10);
insert into produtos (id, nome, descricao, preco) values (3, 'Lychee', 'curae nulla dapibus dolor vel est donec odio justo sollicitudin', 63);
insert into produtos (id, nome, descricao, preco) values (4, 'Emulsifier', 'varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar', 25);
insert into produtos (id, nome, descricao, preco) values (5, 'Absolut Citron', 'donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id', 6);
insert into produtos (id, nome, descricao, preco) values (6, 'Juice - Lime', 'in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam', 96);
insert into produtos (id, nome, descricao, preco) values (7, 'Flower - Carnations', 'in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis', 90);
insert into produtos (id, nome, descricao, preco) values (8, 'Carbonated Water - Wildberry', 'molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in', 20);
insert into produtos (id, nome, descricao, preco) values (9, 'Bay Leaf', 'a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam', 61);
insert into produtos (id, nome, descricao, preco) values (10, 'Coffee Swiss Choc Almond', 'nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a', 80);
insert into produtos (id, nome, descricao, preco) values (11, 'Pumpkin - Seed', 'ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes', 63);
insert into produtos (id, nome, descricao, preco) values (12, 'Peas Snow', 'in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum', 10);
insert into produtos (id, nome, descricao, preco) values (13, 'Crush - Grape, 355 Ml', 'ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit', 37);
insert into produtos (id, nome, descricao, preco) values (14, 'Appetizer - Mango Chevre', 'posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a', 83);
insert into produtos (id, nome, descricao, preco) values (15, 'Tea - Lemon Green Tea', 'est quam pharetra magna ac consequat metus sapien ut nunc', 8);
insert into produtos (id, nome, descricao, preco) values (16, 'Crab - Dungeness, Whole, live', 'mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo', 72);
insert into produtos (id, nome, descricao, preco) values (17, 'Wine - Delicato Merlot', 'ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean', 35);
insert into produtos (id, nome, descricao, preco) values (18, 'Beans - Yellow', 'donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst', 5);
insert into produtos (id, nome, descricao, preco) values (19, 'Nantucket - Kiwi Berry Cktl.', 'lectus in est risus auctor sed tristique in tempus sit amet sem', 17);
insert into produtos (id, nome, descricao, preco) values (20, 'Ecolab - Mikroklene 4/4 L', 'morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla', 69);
insert into produtos (id, nome, descricao, preco) values (21, 'V8 Splash Strawberry Banana', 'erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea', 54);
insert into produtos (id, nome, descricao, preco) values (22, 'Maple Syrup', 'eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu', 65);
insert into produtos (id, nome, descricao, preco) values (23, 'Nut - Peanut, Roasted', 'non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac', 24);
insert into produtos (id, nome, descricao, preco) values (24, 'Juice - Apple Cider', 'urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat', 78);
insert into produtos (id, nome, descricao, preco) values (25, 'Venison - Racks Frenched', 'proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem', 65);
insert into produtos (id, nome, descricao, preco) values (26, 'Pepper - Green', 'ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra', 67);
insert into produtos (id, nome, descricao, preco) values (27, 'Bread - Malt', 'pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue', 9);
insert into produtos (id, nome, descricao, preco) values (28, 'Pepperoni Slices', 'gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer', 74);
insert into produtos (id, nome, descricao, preco) values (29, 'Flavouring - Raspberry', 'convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien', 97);
insert into produtos (id, nome, descricao, preco) values (30, 'Chilli Paste, Sambal Oelek', 'vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit', 53);
insert into produtos (id, nome, descricao, preco) values (31, 'Coffee - Flavoured', 'fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in', 13);
insert into produtos (id, nome, descricao, preco) values (32, 'Pomello', 'varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel', 69);
insert into produtos (id, nome, descricao, preco) values (33, 'Wine - Duboeuf Beaujolais', 'consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl', 10);
insert into produtos (id, nome, descricao, preco) values (34, 'Rice - Long Grain', 'felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel', 11);
insert into produtos (id, nome, descricao, preco) values (35, 'Puff Pastry - Sheets', 'odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat', 23);
insert into produtos (id, nome, descricao, preco) values (36, 'Sobe - Orange Carrot', 'rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam', 99);
insert into produtos (id, nome, descricao, preco) values (37, 'Liqueur - Melon', 'id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit', 14);
insert into produtos (id, nome, descricao, preco) values (38, 'Turkey - Ground. Lean', 'erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero', 98);
insert into produtos (id, nome, descricao, preco) values (39, 'Sauce - Gravy, Au Jus, Mix', 'consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis', 6);
insert into produtos (id, nome, descricao, preco) values (40, 'Buffalo - Tenderloin', 'venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in', 77);
insert into produtos (id, nome, descricao, preco) values (41, 'Olives - Nicoise', 'ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris', 12);
insert into produtos (id, nome, descricao, preco) values (42, 'Pineapple - Regular', 'nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque', 25);
insert into produtos (id, nome, descricao, preco) values (43, 'Spinach - Spinach Leaf', 'elit proin risus praesent lectus vestibulum quam sapien varius ut blandit non interdum', 4);
insert into produtos (id, nome, descricao, preco) values (44, 'Beef - Diced', 'nisi eu orci mauris lacinia sapien quis libero nullam sit amet', 21);
insert into produtos (id, nome, descricao, preco) values (45, 'Vermacelli - Sprinkles, Assorted', 'lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat', 100);
insert into produtos (id, nome, descricao, preco) values (46, 'Wine - Zinfandel Rosenblum', 'molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in', 5);
insert into produtos (id, nome, descricao, preco) values (47, 'Buttons', 'molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci', 25);
insert into produtos (id, nome, descricao, preco) values (48, 'Hersey Shakes', 'ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim', 43);
insert into produtos (id, nome, descricao, preco) values (49, 'White Baguette', 'ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere', 63);
insert into produtos (id, nome, descricao, preco) values (50, 'Energy Drink Bawls', 'volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet', 98);
